545 new arithmetization
NilFoundation/zkllvm-transpiler pull request #74
Opened 2024-02-28 14:20 UTC by CblPOK-git

2024-03-06 07:14 UTC, ETatuzova requested changes

2024-03-06 07:14 UTC, ETatuzova commented on test/transpiler.cpp
Transpiler lib tests should be fixed.
We cannot check full functionality only with zkllvm examples.

Some scripts for perfect in-EVM and recusion testing are in this issue: https://github.com/NilFoundation/zkllvm-transpiler/issues/67

2024-03-06 15:32 UTC, CblPOK-git commented on test/transpiler.cpp
done, test run was successful, also added this test into zkllvm CI

2024-03-07 13:33 UTC, ETatuzova requested changes

2024-03-07 13:33 UTC, ETatuzova commented on include/nil/blueprint/transpiler/recursive_verifier_generator.hpp
>                          full_public_input_check_str += "\tresult = pallas::base_field_type::value_type(0);\n";
Move it before 
`for( std::size_t j = 0; j < public_input_sizes[i]; j++){`

2024-03-07 16:44 UTC, ETatuzova approved these changes

2024-03-07 16:50 UTC, merged